### ISSUE TITLE
Research TypeScript and React

### ISSUE THREAD

**Issue by UO276244** [Arquisoft/dede_en3a#1]
In order to being able to develop the best project possible, we decided to make research on React and TypeScript in order to start the prototype in the best conditions possible.

**Comment by UO276824** [comment]
Possible videos in order to learn.

Typescript video: https://www.youtube.com/watch?v=BwuLxPH8IDs
React video: https://www.youtube.com/watch?v=Dorf8i6lCuk

**Comment by UO276244** [comment]
Here i let a pseudo-tutorial (in spanish) to install NODE, React should already be added to the project once you clone the repo
[Como Instalar NODE, REAT Y TYPESCRIPT.pdf](https://github.com/Arquisoft/dede_en3a/files/7997477/Como.Instalar.NODE.REAT.Y.TYPESCRIPT.pdf)

**Comment by UO277912** [comment]
I have a problem when trying to configure node as the interpreter of WebStorm, it doesn't appear as it says in the pdf. Any idea of what could it be?

**Comment by UO276824** [comment]
If you refer to the point 5 of the PDF, I think that the problem can be solved just restarting the WebStorm app. That may be happening because you might have installed Node while having WebStorm open and it did not detected the right path.
