### ISSUE TITLE
On bought order send email with the information

### ISSUE THREAD

**Issue by UO276824** [Arquisoft/dede_en3a#115]

**Comment by UO276824** [comment]
https://edigleyssonsilva.medium.com/cloud-functions-for-firebase-sending-e-mail-1f2631d1022e

**Comment by UO276244** [comment]
https://firebase.google.com/products/extensions/firebase-firestore-send-email

**Comment by UO276244** [comment]
https://www.youtube.com/watch?v=sV0FT8cf4F8

**Comment by UO276244** [comment]
https://support.google.com/mail/answer/185833?hl=
