### ISSUE TITLE
Problem with Acceptance Tests

### ISSUE THREAD

**Issue by UO277912** [Arquisoft/dede_en3a#139]
I have a problem with the execution of the acceptance tests.

This is the "test:e2e" line of the package package.json:
 "test:e2e": "start-server-and-test 'npm start' http://localhost:3000 prod 3000 'cd e2e && jest '",

As you can see here, it finds the test but it doesn't execute it.
![image](https://user-images.githubusercontent.com/78622200/164910192-6273cede-67a4-4491-8d0f-5cfb0fd3c49a.png)

And this is the structure of the e2e tests
![image](https://user-images.githubusercontent.com/78622200/164910258-33dc11e1-338a-4487-a440-7e1eb520df6f.png)

I am not able to execute it, I think the test format is fine, as it is almost the one you provided us and I would appreciate any help.

Thanks in advance.

**Comment by pglez82** [comment]
Tell me the branch where these tests are

**Comment by UO277912** [comment]
They are in "acceptanceTests"

**Comment by UO277912** [comment]
The tests were not pushed, now they are

**Comment by pglez82** [comment]
In my system the test is found:

![image](https://user-images.githubusercontent.com/10683040/164911337-4a6ff9f4-cd24-443e-8933-0cbe6444f3d3.png)

Remember that the extension should be .ts, as it is indicated in the e2e/jest-config file.

Just cloned the repo, checkout the branch, npm install and npm test:e2e.

**Comment by pglez82** [comment]
Maybe it is something related with the operating system:

https://github.com/facebook/jest/issues/7914

It is an open bug so maybe the problem is that. You can check the proposed solutions in the issue to see if they work.

**Comment by UO277912** [comment]
I have been using this jest.config.ts:
![image](https://user-images.githubusercontent.com/78622200/164912565-9281177f-4897-45fd-a6f4-3e96ab8be23b.png)

But I am obtaining the same problem: the test is detected but not executed.
![image](https://user-images.githubusercontent.com/78622200/164912609-3efe0356-2e4f-412a-8b73-d3f15a2b7bd1.png)

**Comment by UO277912** [comment]
And I also tried to clone again the repo, checkout the branch, npm install and execute the tests.

**Comment by pglez82** [comment]
> "test:e2e": "start-server-and-test 'npm start' http://localhost:3000 prod 3000 'cd e2e && jest '",

This is line is not correct (but I don't think is the cause that your tests are not executed.
You are launching the webapp with npm start and then the production version with `prod`. That is, you are launching the webapp twice. In your case the line should be: 

```
"test:e2e": "start-server-and-test prod 3000 'cd e2e && jest '"
```

**Comment by pglez82** [comment]
Change the test:e2e command, run npm run build and then npm run test:e2e and post the full output here to see if I can find something

**Comment by UO277912** [comment]
![image](https://user-images.githubusercontent.com/78622200/164913244-f081367a-a896-42e8-bb7e-d3d5b35fe385.png)

**Comment by pglez82** [comment]
Can you test the option:

watchman: false

in e2e/jest-config.ts

**Comment by UO277912** [comment]
With this jest.config.ts:
![image](https://user-images.githubusercontent.com/78622200/164914357-a6153b8f-4a0a-4b0c-a2d0-0db73c3657c2.png)

The same output:
![image](https://user-images.githubusercontent.com/78622200/164914391-4a6225bf-3506-4b7f-a1f7-11090730ac58.png)

**Comment by UO277912** [comment]
Sorry, it should be "false" as boolean and not string, but the output is the same

**Comment by pglez82** [comment]
Ok. I got the problem. I had to set up a windows VM to reproduce the issue. Without it I had no chance.

The problem is that Windows does not like the `cd e2e && jest`. && in linux is used to execute two commands together, but it does not work on Windows. The solution is to launch the tests in a different way:

```
"test:e2e": "start-server-and-test prod 3000 'jest --rootDir=e2e --config=./e2e/jest.config.ts'"
```
With this, test will be found.

A few extra things: 

- having a jest-config.ts in the webapp equal to the one that you have in e2e is wrong. That will mess up unitary tests. It was very confusing for me as it was taking this configuration file instead of the one in e2e.
- You have a package.json outside in the root directory of the repo. I do not understand why.
- There are files with extension js and ts with the same name.
I think it is time your team spend some time cleaning a little bit the repo.

Let me know if the solution works

**Comment by UO277912** [comment]
Yes, now I can execute the tests. Thank you so much Pablo!!

**Comment by UO277912** [comment]
Hello Pablo, I am having problems again with the tests. After doing some final configuration on the first test, it is now opening a browser with the page as expected. The problem is that it is not finding the elements on the page. The way of looking for them is the same as the one you provided us, but I am looking for a "div" instead of a "button". I have tried with "division", "div", the name of the element, giving them an id, but nothing seems to work and I am not finding useful information at all.

![image](https://user-images.githubusercontent.com/78622200/165138245-e61c4814-4f63-4c33-8f38-6794eeba8150.png)

Something that I don't know if may cause the problem is that the test opens 2 tabs on the browser, one with the page and one empty, and maybe it is looking for the elements there.

![image](https://user-images.githubusercontent.com/78622200/165138645-1fd8cec0-f407-4701-ac21-af9cce117e52.png)

**Comment by UO277912** [comment]
Some alternative ways with no result: https://github.com/smooth-code/jest-puppeteer/issues/84

**Comment by UO277912** [comment]
I found how can I do it Pablo, using this: await expect(page).toClick('div[title="shop"]')

Sorry for all the messages

**Comment by pglez82** [comment]
I am glad you found the problem your self. Sometimes it could be difficult to find some selectors for some page elements. Good job!

**Comment by pglez82** [comment]
Maybe this issue can be closed. If you have other problems with acceptance tests you can open a new one. It is easier to follow issues that way.
