### ISSUE TITLE
Research INRUPT github

### ISSUE THREAD

**Issue by UO276244** [Arquisoft/dede_en3a#26]
Check https://github.com/inrupt and try some libraries for using pods.

**Comment by UO276244** [comment]
https://docs.inrupt.com/developer-tools/javascript/react-sdk/

**Comment by UO276244** [comment]
npm install @mui/material @emotion/react @emotion/styled

**Comment by carlosgarriga12** [comment]
https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/getting-started/
