### ISSUE TITLE
Add redux to react app

### ISSUE THREAD

**Issue by EnzoBarbon** [Arquisoft/dede_en3a#29]
Install and implement redux in the react application.

**Comment by UO277912** [comment]
Create store, reducer and necessary classes for redux -> https://es.acervolima.com/como-persistir-el-estado-de-redux-en-el-almacenamiento-local-sin-ninguna-biblioteca-externa/

**Comment by EnzoBarbon** [comment]
https://www.codementor.io/@rajjeet/step-by-step-how-to-add-redux-to-a-react-app-11tcgslmvi

**Comment by Pelayo21** [comment]
https://www.freecodecamp.org/news/how-to-use-redux-in-your-react-typescript-app/
