### ISSUE TITLE
Information about continuous integration

### ISSUE THREAD

**Issue by Pelayo21** [Arquisoft/dede_en3a#73]
Here all the links with the documentation about continuous integration will be stored.

Link for continuous integration: https://docs.github.com/es/actions/automating-builds-and-tests/about-continuous-integration

Link for GitHub actions: https://docs.github.com/es/actions

Link for GitHub actions as a feature: https://github.com/features/actions

Links for GitHub secrets: 

https://docs.github.com/es/actions/using-workflows/sharing-workflows-secrets-and-runners-with-your-organization#sharing-secrets-within-an-organization

**Comment by Pelayo21** [comment]
Here I leave a repository that contains a list of CI starter worflows:
https://github.com/actions/starter-workflows/tree/main/ci

**Comment by Pelayo21** [comment]
If we are going to use Actions, the best option will be taking them from the Marketplace and then custom them. For that reason, this little guide will be helpful:
https://docs.github.com/es/actions/learn-github-actions/finding-and-customizing-actions

**Comment by Pelayo21** [comment]
How to run a workflow:
https://docs.github.com/en/enterprise-server@3.1/actions/managing-workflow-runs/manually-running-a-workflow

**Comment by Pelayo21** [comment]
We should put in the documentation the hosting service used, for example it could be 'ubuntu-latest'.

We have to be careful with the node version, to know the node version use 'node -v' command.

**Comment by Pelayo21** [comment]
About CLI in GitHub:
https://docs.github.com/es/github-cli/github-cli/about-github-cli

How to use CLI:
https://docs.github.com/es/actions/using-workflows/using-github-cli-in-workflows

**Comment by Pelayo21** [comment]
Firebase Hosting: 
https://firebase.google.com/docs/hosting?authuser=1&hl=es

**Comment by carlosgarriga12** [comment]
https://firebase.google.com/docs/hosting/github-integration

**Comment by carlosgarriga12** [comment]
https://javascript.plainenglish.io/how-to-automate-firebase-app-deployment-with-github-actions-beb26e458e17

**Comment by Pelayo21** [comment]
A solution approach to our problem: https://github.com/actions/upload-artifact/issues/232

**Comment by Pelayo21** [comment]
Succesful workflow but without anyything deployed: https://github.com/Arquisoft/dede_en3a/actions/runs/2102096786

**Comment by UO276244** [comment]
https://github.com/lowply/deploy-firebase
