### ISSUE TITLE
Start section 8 of documentation: Cross-cutting Concepts

### ISSUE THREAD

**Issue by UO276244** [Arquisoft/dede_en3a#8]
We will use LucidChart to design the domain model.

**Comment by carlosgarriga12** [comment]
Here is the link for editing the domain model:  https://lucid.app/lucidchart/acb3145c-74b9-45fa-b321-400ba19ebab3/edit?invitationId=inv_a5c4ff08-686e-4a1f-af2a-c3b46dc42a41

**Comment by UO277912** [comment]
Link to the documentation section -> https://arquisoft.github.io/dede_en3a/#section-concepts

**Comment by UO277912** [comment]
Elements of the domain model -> user, order, POD and product
